network/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required


from . import views

app_name = "network"

urlpatterns = [
    path("following", views.following, name="following"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("user/<slug:slug>", login_required(views.ProfileDetailView.as_view()), name="profile-detail"),
    path("user/<slug:slug>/image", login_required(views.ProfileImage.as_view()), name="profile-image"),
    path("", views.index, name="index"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("network.rest_urls")),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.deletion import CASCADE

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls.base import reverse
from django.utils.formats import date_format


class User(AbstractUser):

    def __str__(self) -> str:
        return self.email


class Followers(models.Model):
    # the one who follows
    follower = models.ForeignKey(
        to=User, on_delete=CASCADE, related_name="follows")
    # the one who is followed
    followee = models.ForeignKey(
        to=User, on_delete=CASCADE, related_name="followers")
    # when was relationship established
    created = models.DateTimeField('date created', auto_now_add=True)

    def __str__(self) -> str:
        return self.follower.username + " -> " + self.followee.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE, primary_key=True)
    slug = models.SlugField("profile url")
    dob = models.DateTimeField('date of birth', null=True, blank=True)
    avatar_url = models.URLField("profile img url", null=True, blank=True, default="https://i.ibb.co/Y8DFbBv/mee6.png")

    def __str__(self) -> str:
        return self.user.email


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance, slug=instance.username)
    pass


class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=CASCADE)
    body = models.TextField(max_length=1000, blank=False)
    created = models.DateTimeField('date created', auto_now_add=True)
    edited = models.DateTimeField('date edited', auto_now=True, blank=True, null=True)

    def __str__(self) -> str:
        return self.author.username + " @ [" + date_format(self.created, "DATETIME_FORMAT") + "]"

    def serialize(self) -> dict:
        '''Transforms Post model into JSON object'''
        post = {}

        post["id"] = self.id
        post["author"] = {
            "id": self.author.id,
            "username": self.author.username,
            "avatar": self.author.profile.avatar_url,
        }
        post["body"] = self.body
        post["created"] = {
            "short": date_format(self.created, "d M"),
            "long": date_format(self.created, "DATETIME_FORMAT"),
        }
        post["numberOfLikes"] = self.likes.count()
        post["postURL"] = reverse("network-api:post-detail-api", args=[self.id])
        post["likeURL"] = reverse("network-api:post-like-api", args=[self.id])
        post["profileURL"] = reverse("network:profile-detail", args=[self.author.profile.slug])
        
        return post

    def number_of_likes(self) -> int:
        return self.likes.count()


class Upvotes(models.Model):
    # Any user can upvote any post
    user = models.ForeignKey(User, on_delete=CASCADE)
    post = models.ForeignKey(Posts, on_delete=CASCADE, related_name="likes")
    created = models.DateTimeField('date created', auto_now_add=True)

    def __str__(self) -> str:
        return self.user.username + "->" + self.post.__str__()


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    post = models.ForeignKey(Posts, on_delete=CASCADE)
    body = models.TextField(max_length=1000)
    created = models.DateField('date created', auto_now_add=True)

    def __str__(self) -> str:
        return self.body[0:10] + "->" + self.post.__str__()

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.http.response import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views import View

from .helpers import is_valid_or_error
from .models import Profile, User

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("network:login"))

    return render(request, "network/home.html")


def following(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("network:login"))


    return render(request, "network/following.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("network:logout"))
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        if username in ["login", "logout", "register", "index", "admin"]:
            return render(request, "network/register.html", {
                "message": "This username is not allowed"
            })

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        if not username or not email or not password or not confirmation:
            return render(request, "network/register.html", {
                "message": "All fields must be filled."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")


class ProfileDetailView(DetailView):
    model = Profile
    template_name = "network/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['followers'] = [relation.follower for relation in context["profile"].user.followers.all()]
        context['follows'] = [relation.followee for relation in context["profile"].user.follows.all()]
        return context


class ProfileImage(View):

    def delete(self, request, slug):
        profile = Profile.objects.filter(slug=slug)
        if profile.exists():
            profile = profile.first()
            if request.user == profile.user:
                profile.avatar_slug = ""
                profile.save()
                return JsonResponse({"msg": "User's profile was successfully updated"})
            return JsonResponse({"error": "User can only update own profile"}, status=401)
        return JsonResponse({"error": "Profile to be updated does not exist"}, status=400)


    def put(self, request, slug):
        reqBody = json.loads(request.body)
        avatar_url = reqBody.get("avatarUrl")
        if avatar_url:
            profile = Profile.objects.filter(slug=slug)
            if profile.exists():
                profile = profile.first()
                if request.user == profile.user:
                    profile.avatar_url = avatar_url
                    validation = is_valid_or_error(profile)
                    if validation is True:
                        profile.save()
                        return JsonResponse({"msg": "User's profile was successfully updated"})
                    return JsonResponse({"error": "Inserted URL is not valid URL"}, status=400)
                return JsonResponse({"error": "User can only update own profile"}, status=401)
            return JsonResponse({"error": "Profile to be updated does not exist"}, status=400)
        return JsonResponse({"error": "Param 'avatarUrl' not found in request body"}, status=400)

network/templates/network/following.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    <div class="row cols-1 justify-content-center">
        <div class="col-8">
            {% include "network/post_form.html" %}
            <div id="postsList" class="row cols-1 py-3 gy-3 justify-content-center">
                {% comment %} POSTS COME HERE {% endcomment %}
            </div>
        </div>
    </div>
    <script>
    document.addEventListener("DOMContentLoaded", () => {
        const [currentPage, setCurrentPage] = useState(1);
        loadPosts(currentPage, setCurrentPage, {following: true})
    });
    </script>
{% endblock %}

network/templates/network/home.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    <div class="row cols-1 justify-content-center">
        <div class="col-8">
            {% include "network/post_form.html" %}
            <div id="postsList" class="row cols-1 gy-3 py-3 justify-content-center">
                {% comment %} POSTS GO HERE {% endcomment %}
            </div>
        </div>
    </div>
    <script>
    document.addEventListener("DOMContentLoaded", () => {
        const [currentPage, setCurrentPage] = useState(1);
        loadPosts(currentPage, setCurrentPage);
    });
    </script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Bootstrap CSS -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
            crossorigin="anonymous"
        />

        <!-- FontAwesome CSS -->
        <link
            rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
            integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk"
            crossorigin="anonymous"
        />
        <!-- Custom CSS -->
        <link href="{% static 'network/styles.css' %}" rel="stylesheet" />
        <link rel="shortcut icon" type="image/png" href="{% static 'network/favicon.ico' %}"/>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light px-3 mb-3">
            <a class="navbar-brand" href="{% url 'network:index' %}">Peeper</a>

            <ul class="navbar-nav mr-auto w-100 align-items-center">

                <li class="spacer"></li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'network:following' %}">Following</a>
                </li>

                <li class="spacer"></li>

                <li class="nav-item">
                    <a
                        class="nav-link"
                        style="display: inline-block"
                        href="{% url 'network:profile-detail' user.profile.slug %}"
                    >
                        {% if user.profile.avatar_url %}
                        <img
                            style="display: inline-block"
                            src="{{ user.profile.avatar_url }}"
                            width="32px"
                            height="32px"
                            alt="{{ user.username }}'s profile picture"
                            class="rounded-circle"
                        />
                        {% else %}
                        <i class="fas fa-user-circle fa-lg"></i>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'network:logout' %}"
                        >Log Out</a
                    >
                </li>
                {% else %}
                

                <li class="nav-item dropdown dropstart">
                    <a href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle fa-2x"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'network:login' %}">Log In</a></li>
                        <li><a class="dropdown-item" href="{% url 'network:register' %}">Register</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </nav>
        <main class="container-md">{% block body %} {% endblock %}</main>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
            crossorigin="anonymous"
        ></script>

        <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.0/dist/js.cookie.min.js"></script>
        <script
            src="{% static 'network/script.js' %}"
            type="text/javascript"
        ></script>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}
    <div class="col-4 mx-auto">


    <h2 class="text-center" >Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post" class="vstack gap-1 my-2" >
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

    </div>
{% endblock %}

network/templates/network/post.html
<div class="card">
    <div class="row gx-0">
        {% comment %} CARD LEFT START {% endcomment %}
        <div class="col-auto d-flex justify-content-center" style="width: 4em">
            <i class="fas fa-user-circle fa-3x my-2"></i>
        </div>
        {% comment %} CARD LEFT END {% endcomment %}

        {% comment %} CARD RIGHT START {% endcomment %}
        <div class="col px-2">
            {% comment %} HEADER START {% endcomment %}
            <div class="py-1 d-flex align-items-center">            
                <a class="link-dark fw-bold" href="{{ post.profileURL }}">
                    {{ post.author.username }}
                </a>
                <span class="card-title-divider text-muted"></span>
                <a
                    href="#"
                    class="link-dark text-muted"
                    data-bs-toggle="tooltip"
                    data-bs-html="true"
                    title="<b>{{ post.created.long }}</b>"
                >
                    {{ post.created.short }}
                </a>
                <span class="spacer"></span>
                {% if post.userIsAuthor %}
                <span class="dropdown">
                    <button
                        class="btn btn-sm"
                        type="button"
                        id="postOptions{{post.id}}"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        <i class="fas fa-ellipsis-h"></i>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="postOptions{{post.id}}">
                        <li>
                            <a class="dropdown-item" href="#" onclick='editPost(event, "{{post.postURL}}", {{post.id}})' >Edit</a>
                        </li>
                        <li>
                            <a class="dropdown-item text-danger" href="#" onclick='deletePost("{{post.postURL}}", {{post.id}})' >Delete</a>
                        </li>
                    </ul>
                </span>
                {% endif %}
            </div>
            {% comment %} HEADER END {% endcomment %}

            {% comment %} BODY START {% endcomment %}
            <div class="py-1">
                <p class="card-text">{{ post.body }}</p>
            </div>
            {% comment %} BODY END {% endcomment %}
            

            {% comment %} FOOTER START {% endcomment %}
            <form class="py-1" onsubmit='likePost(event, "{{post.likeURL}}", {{post.id}})'>                     
                    <button
                        type="button"
                        onclick='likePost(event, "{{post.likeURL}}", {{post.id}})'
                        class="btn btn-sm rounded-circle text-danger"
                        data-like-url={{post.likeURL}}
                        data-post-id={{post.id}}
                        data-user-like={% if post.userLikesThis %}"true"{% else %}"false"{% endif %} {% if post.userIsAuthor %}disabled{% endif %}>
                    </button>
                    <input type="submit" hidden />
                    <span class="card-text mr-2">
                        <small class="text-muted" data-like-count={{ post.numberOfLikes }}>
                            {{ post.numberOfLikes }}
                        </small>
                        <small class="text-muted">
                            like{{ post.numberOfLikes|pluralize }}
                        </small>
                    </span>
            </form>
            {% comment %} FOOTER END {% endcomment %}
        </div>
        {% comment %} CARD RIGHT END {% endcomment %}
    </div>    
</div>

network/templates/network/post_form.html
<form id="newPostForm" class="mb-5">
    <div class="mb-3">
        <label for="postBody" class="form-label"><span class="visually-hidden">New tweet<span></label>
        <textarea
            class="form-control"
            id="postBody"
            name="post_body"
            rows="3"
        ></textarea>
    </div>
    <button type="submit" class="btn btn-sm btn-primary">Peep it!</button>
</form>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const newPostForm = document.getElementById("newPostForm");
        newPostForm.addEventListener("submit", submitNewPost, false);
    })
</script>

network/templates/network/profile.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    <div class="row cols-1 justify-content-center">
        <div class="col-8">
            <div class="vstack gap-1 mx-auto text-center align-items-center">
                {% comment %} Profile image wrapper {% endcomment %}
                <div class="profile-img-wrapper">
                    {% comment %} User's avatar {% endcomment %}                    
                    <img 
                    class="rounded-circle"
                    src={% if object.user.profile.avatar_url %} "{{ object.user.profile.avatar_url }}" {% else %} "https://i.ibb.co/LYx289M/octopus-colored.jpg" {% endif %}
                    width="280px" 
                    height="280px" 
                    alt="{{ object.user.username }}'s profile picture" 
                    />
                    {% comment %} Add new URL img overlay {% endcomment %}
                    {% if object.user == user %}
                    <div class="profile-img-overlay">
                        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modal">
                            Add custom image
                        </button>
                    </div>
                    {% endif %}
                </div>
                <h3>
                {% if object.user.first_name and object.user.last_name %}
                    {{ object.user.first_name }} '{{ object.user.username }}' {{ object.user.last_name }}
                {% else %}
                    {{ object.user.username }}
                {% endif %}
                </h3>
                <div class="hstack gap-3 justify-content-center">
                    <div>
                        <i class="fas fa-users"></i>
                        <span>{{followers|length}} follower{{ followers|length|pluralize }}</span>
                    </div>
                    
                    <div>
                        <i class="fas fa-user-friends"></i>
                        <span>{{follows|length}} following</span>
                    </div>

                    {% if object.user != user %}
                    <button class="btn btn-sm btn-light" id="followBtn" data-action={% if user not in followers %}"follow"{% else %}"unfollow"{% endif %} data-username={{object.user.username}}>
                        {% if user in followers %}
                            <i class="fas fa-user-minus"></i>
                            Unfollow
                        {% else %}
                            <i class="fas fa-user-plus"></i>
                            Follow  
                        {% endif %}                         
                    </button>
                    <script>
                        document.addEventListener("DOMContentLoaded", () => {
                            const followBtn = document.getElementById("followBtn");
                            const followListener = followUser;
                            followBtn.addEventListener("click", followListener);
                        })
                    </script>
                    {% endif %}
                </div>
            </div>
            {% if object.user == user %}
                {% include "network/post_form.html" %}
            {% endif %}
            <div id="postsList" class="row cols-1 gy-3 py-3 justify-content-center">
                {% comment %} POSTS GO HERE {% endcomment %}
            </div>
        </div>
    </div>
    {% comment %} MODAL {% endcomment %}
    {% if object.user == user %}
    <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="profileImgModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="profileImgModal">Insert custom profile image</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="profileImgForm">
                    <input class="form-control" type="text" placeholder="Image's absolute URL eg. https://stock.com/octopus.jpg" />
                    <button type="submit" hidden />
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="profileImgFormBtn" type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
        const profileImgForm = document.getElementById("profileImgForm");
        const profileImgFormBtn = document.getElementById("profileImgFormBtn");

        profileImgForm.addEventListener("submit", editProfileImg);
        profileImgFormBtn.addEventListener("click", editProfileImg);
        })
    </script>
    {% endif %}
    
    <script>
    document.addEventListener("DOMContentLoaded", () => {
        const [currentPage, setCurrentPage] = useState(1);
        loadPosts(currentPage, setCurrentPage, {singleUser: "{{ object.user.username }}"});
    });
    </script>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <div class="col-4 mx-auto">

    <h2 class="text-center" >Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post" class="vstack gap-1 my-2">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

    </div>
{% endblock %}